# Generated by Django 4.2.7 on 2023-11-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salama_customers',
            new_name='salama',
        ),
    ]
