# Generated by Django 4.2.7 on 2023-11-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0002_rename_salama_customers_salama'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salama',
            table='salama',
        ),
    ]
