# Generated by Django 4.2.7 on 2023-11-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0003_alter_salama_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salama',
            table='salama_customers',
        ),
    ]
