# Generated by Django 4.2.7 on 2023-11-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0007_alter_orderform_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderform',
            old_name='first_name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderform',
            old_name='last_name',
            new_name='quantity',
        ),
    ]
