# Generated by Django 4.2.7 on 2023-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0008_rename_first_name_orderform_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='route',
            field=models.CharField(max_length=50),
        ),
    ]
