# Generated by Django 4.2.7 on 2023-11-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0010_orderform_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderform',
            table='salama_order',
        ),
    ]
