# Generated by Django 4.2.7 on 2023-11-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0012_orderform_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={'ordering': ['user', 'item', 'description', 'quantity', 'route']},
        ),
    ]
