# Generated by Django 4.2.7 on 2023-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salama', '0014_alter_orderform_options_remove_orderform_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={},
        ),
    ]
